---

# Security settings
security:
  token: lstbknd

workdir: /${HOME}/.lastbackend/
rootless: false

# Http-server settings
server:
  host: 0.0.0.0
  port: 2992
  tls:
    verify: false
    ca: ""
    cert: ""
    key: ""