sudo: required
language: go

services:
  - docker

go:
  - 1.11.x

before_install:
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.2.9/etcd-v3.2.9-linux-amd64.tar.gz -o etcd-v3.2.9-linux-amd64.tar.gz
  - tar xzvf etcd-v3.2.9-linux-amd64.tar.gz
  - ./etcd-v3.2.9-linux-amd64/etcd >> /dev/null&

before_script:
  - env GO111MODULE=on make test

script:
  - env GO111MODULE=on make build

after_success:
  - make docs

notifications:
  slack: $ST_TOKEN

deploy:
  - provider: pages
    local_dir: docs/output
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
