---

# Runtime
verbose: 3

# Etcd database
storage:
  driver: "etcd"
  etcd:
    prefix: lastbackend
    endpoints:
      "127.0.0.1:2379"

# Last.Backend vault service settings
vault:
  endpoint: http://127.0.0.1:2965
  token: fca7678528b749db863d04cd9ec27d89