---
# Runtime
verbose: 3
token: lstbknd

server:
  host: 0.0.0.0
  port: 2964
  tls:
    insecure: true

logger:
  host: 0.0.0.0
  port: 2966
  workdir: /opt/logs

api:
  uri: "127.0.0.1:2967"
  tls:
    insecure: true